### ISSUE TITLE
0.6.1 on crates.io is a breaking change

### ISSUE THREAD

**Issue by mvojacek** [jaynus/amethyst-imgui#11]
0.6.0 depends on amethyst ^0.13.0
0.6.1 depends on amethyst ^0.14.0

This is a breaking change, as ^0.6.0 may choose to use either 0.6.1 or 0.6.0, possibly making a project depend on two distinct incompatible amethyst versions.

**Comment by jaynus** [comment]
closing due to version bump in #14
