### ISSUE TITLE
Window resize/fullscreen breaks UI

### ISSUE THREAD

**Issue by ssokolen** [jaynus/amethyst-imgui#16]
Not sure if this is a general issue or not, but switching overall window size or enabling full screen breaks the displayed UI. The issue is reproducible with the demo_overlay example:

`cargo run --example demo_overlay --features vulkan`

It appears that although window size parameters and font are scaled with the new width, the old width is retained in the context of ui positioning (creating a dead space where the window got expanded and resulting in some elements popping off entirely "off-screen" into this dead space). Amethyst itself and amethyst_gui have no issues with the resize.

Is this a bug or do I need to set up resize options/flags? If it's the latter, some guidance would be appreciated.

Before resize:

![image](https://user-images.githubusercontent.com/1260441/87889392-c52f1380-ca07-11ea-90d8-2d0b0d57e406.png)

After resize

![image](https://user-images.githubusercontent.com/1260441/87889401-d8da7a00-ca07-11ea-9126-15ed23787d89.png)

**Comment by Carbonhell** [comment]
Hello, I had this problem as well and I've tried analyzing the code regarding the RenderImgui plugin.
There's this particular line of code: https://github.com/amethyst/amethyst-imgui/blob/master/src/lib.rs#L55
Basically, the events regarding the window aren't being passed to the platform, this includes the WindowEvent::Resized(), simply uncommenting the line makes resizing work perfectly. I assume there's some sort of drawback, but I've yet to find it.
Hope this helps you.

**Comment by ghost** [comment]
I also had this issue when using imgui, but didn't actually know if it was the plugin error or the imgui one.

**Comment by vladbat00** [comment]
Sorry it took me a while to look into the problem. I remember seeing this bug in Grumpy Visitors too.
I made a fix in #17. Could you please test it and confirm it works correctly for you @ssokolen @ab0v3g4me?

**Comment by ssokolen** [comment]
Totally missed the notification... but yes, that did the trick, thanks!
